import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
export const countryStates = {
  'Venezuela': [
    { value: 'Amazonas', label: 'Amazonas' },
    { value: 'Anzoátegui', label: 'Anzoátegui' },
    { value: 'Apure', label: 'Apure' },
    { value: 'Aragua', label: 'Aragua' },
    { value: 'Barinas', label: 'Barinas' },
    { value: 'Bolívar', label: 'Bolívar' },
    { value: 'Carabobo', label: 'Carabobo' },
    { value: 'Cojedes', label: 'Cojedes' },
    { value: 'Delta Amacuro', label: 'Delta Amacuro' },
    { value: 'Falcón', label: 'Falcón' },
    { value: 'Guárico', label: 'Guárico' },
    { value: 'Lara', label: 'Lara' },
    { value: 'Mérida', label: 'Mérida' },
    { value: 'Miranda', label: 'Miranda' },
    { value: 'Monagas', label: 'Monagas' },
    { value: 'Nueva Esparta', label: 'Nueva Esparta' },
    { value: 'Portuguesa', label: 'Portuguesa' },
    { value: 'Sucre', label: 'Sucre' },
    { value: 'Táchira', label: 'Táchira' },
    { value: 'Trujillo', label: 'Trujillo' },
    { value: 'La Guaira', label: 'La Guaira' },
    { value: 'Yaracuy', label: 'Yaracuy' },
    { value: 'Zulia', label: 'Zulia' },
    { value: 'Dependencias Federales', label: 'Dependencias Federales' },
    { value: 'Distrito Capital', label: 'Distrito Capital' },
  ],
  'Colombia': [
    { value: 'Amazonas', label: 'Amazonas' },
    { value: 'Antioquia', label: 'Antioquia' },
    { value: 'Arauca', label: 'Arauca' },
    { value: 'Atlántico', label: 'Atlántico' },
    { value: 'Bogotá', label: 'Bogotá' },
    { value: 'Bolívar', label: 'Bolívar' },
    { value: 'Boyacá', label: 'Boyacá' },
    { value: 'Caldas', label: 'Caldas' },
    { value: 'Caquetá', label: 'Caquetá' },
    { value: 'Casanare', label: 'Casanare' },
    { value: 'Cauca', label: 'Cauca' },
    { value: 'Cesar', label: 'Cesar' },
    { value: 'Chocó', label: 'Chocó' },
    { value: 'Córdoba', label: 'Córdoba' },
    { value: 'Cundinamarca', label: 'Cundinamarca' },
    { value: 'Guainía', label: 'Guainía' },
    { value: 'Guaviare', label: 'Guaviare' },
    { value: 'Huila', label: 'Huila' },
    { value: 'La Guajira', label: 'La Guajira' },
    { value: 'Magdalena', label: 'Magdalena' },
    { value: 'Meta', label: 'Meta' },
    { value: 'Nariño', label: 'Nariño' },
    { value: 'Norte de Santander', label: 'Norte de Santander' },
    { value: 'Putumayo', label: 'Putumayo' },
    { value: 'Quindío', label: 'Quindío' },
    { value: 'Risaralda', label: 'Risaralda' },
    { value: 'San Andrés y Providencia', label: 'San Andrés y Providencia' },
    { value: 'Santander', label: 'Santander' },
    { value: 'Sucre', label: 'Sucre' },
    { value: 'Tolima', label: 'Tolima' },
    { value: 'Valle del Cauca', label: 'Valle del Cauca' },
    { value: 'Vaupés', label: 'Vaupés' },
    { value: 'Vichada', label: 'Vichada' },
  ],
  'Costa Rica': [
    { value: 'Alajuela', label: 'Alajuela' },
    { value: 'Cartago', label: 'Cartago' },
    { value: 'Guanacaste', label: 'Guanacaste' },
    { value: 'Heredia', label: 'Heredia' },
    { value: 'Limón', label: 'Limón' },
    { value: 'Puntarenas', label: 'Puntarenas' },
    { value: 'San José', label: 'San José' },
  ],
};